name: llama/llama-3.1-8b-hf
type: CausalLM
epochs: 1
per_device_batch_size: 1
real_batch_size: 64
bf16: True
eval_epochs: 1
early_stopping_patience: 3
max_length: 1024
logging_steps: 1
learning_rate: 2e-4